project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
  resources:
    - .well-known/
    - _redirects
    - _headers
website:
  description: "A personal website"
  site-url: https://rorylawless.com
  title: "Rory Lawless"
  repo-url: https://github.com/rorsome/website
  llms-txt: true
  page-footer:
    background: "#fbf5f5"
    foreground: "#070a0c"
    center: |
      Made with [Quarto](https://quarto.org/) in DC.<br>[Website](https://rorylawless.com/) © 2026 by [Rory Lawless](about.qmd) is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
  search: false
  draft-mode: gone
  navbar:
    background: "#24617a"
    foreground: "#fbf5f5"
    right:
      - icon: file-earmark-person-fill
        href: resume.qmd
        aria-label: "Rory's Resume"
        text: " "
      - icon: envelope-at-fill
        href: mailto:rory@rorylawless.com
        aria-label: "Email Rory"
      - icon: bluesky
        href: https://bsky.app/profile/rorylawless.com
        aria-label: "Rory's Bluesky"
      - icon: linkedin
        href: https://www.linkedin.com/in/rory-lawless/
        aria-label: "Rory's LinkedIn"
      - icon: github
        href: https://github.com/RoryLawless
        aria-label: "Rory's GitHub"
format:
  html:
    theme:
      - none
      - assets/custom.scss
    highlight-style: a11y
    code-copy: true
    backgroundcolor: "#fbf5f5"
    mainfont: "Lato"
    fontcolor: "#070a0c"
    fontsize: 14pt
    linkcolor: "#183e4d"
    code-overflow: wrap
    email-obfuscation: references
    include-after-body: html/analytics.html
metadata-files:
  - drafts.yml
